### ISSUE TITLE
item indices need to be contiguous integers starting at 1

### ISSUE THREAD

**Issue by bwpriest** [LLNL/saltatlas#17]
`saltatlas::dhnsw` objects seemingly break during partitioning whenever the keys of the given `ygm::container::map` are something other than the set `[n] = {0, 1, 2, ..., n-1, n}`. I am unsure if this behavior is intended or not. I can imagine instances where one might want different integers to serve as indices, or indeed one might want to use other object types entirely, such as strings. If the current behavior is inherited from `hnswlib`, then we might want to consider 1-to-1 hashing the key types into `[n]` to support this feature.

**Comment by steiltre** [comment]
Do you have code somewhere you can point me to that breaks? The keys should be integers, but I've used string hashes as IDs before. Also, which partitioner are you using?

The one case I remember with things breaking spectacularly is if you provide the same ID twice (e.g., using string hashes as IDs when there are duplicate strings).

**Comment by bwpriest** [comment]
I'm still actively hacking on the code that was throwing errors, but it is not checked in anywhere yet. I was using a `saltatlas::voronoi_partitioner`. The errors being thrown suggested that the partitioner was referencing keys in the given `ygm::container::map` that did not exist, so the container was returning an empty vector point for comparison that caused the distance function to break. It is possible that cause the problem is other than what I suggested above, but fixing the indices to `{0, 1, ... n-1, n}`. Did resolve it. I can send you a pointer to the code once I've finished with it and checked it in somewhere.

**Comment by steiltre** [comment]
I see. The `saltatlas::voronoi_partitioner` may not like non-contiguous integers. I'll look into where that would be happening. 

In general, I recommend using the `saltatlas::metric_hyperplane_partitioner`. The `voronoi_partitioner` can give very imbalanced partitions.

**Comment by steiltre** [comment]
I've started getting occasional segfaults with the `metric_hyperplane_partitioner`. I'll fix it as soon as I can, but you may experience the same issue if you start using it before I can address the issue.

**Comment by bwpriest** [comment]
I'm not sure if it is related, but I've been getting some defaults while querying that I was not able to diagnose. I think I was using the voronoi partitioner though. I'll back off on that for a bit.

**Comment by bwpriest** [comment]
I believe that this issue is no longer current, so I am going to close it.
