### ISSUE TITLE
bug: voronoi_rank and initial_queries argument order is swapped in saltatlas::dhnsw::query and saltatlas::dhnsw_detail::query_engine_impl::query

### ISSUE THREAD

**Issue by bwpriest** [LLNL/saltatlas#18]
In the current state of develop, `saltatlas::dhnsw::query` calls `saltatlas::dhnsw_detail::query_engine_impl::query` and lists `initial_queries` ahead of `voronoi_rank`

https://github.com/LLNL/saltatlas/blob/b448be075eef1905652bd6f46f5c2eb1599ccea4/include/saltatlas/dhnsw/dhnsw.hpp#L48-L53

However, the corresponding `saltatlas::dhnsw_detail::query_engine_impl::query` implementation swaps the two parameters

https://github.com/LLNL/saltatlas/blob/07268803a58496a3cd714252b53a950b4d147777/include/saltatlas/dhnsw/detail/query_engine.hpp#L399-L401

I'm not sure which order is intended, but the two implementations should be changed so that they agree.

**Comment by steiltre** [comment]
Thanks for catching that. The order in query_engine was the intended order. Fix will be up shortly.

**Comment by steiltre** [comment]
Fixed this issue in [PR #19](https://github.com/LLNL/saltatlas/pull/19)
